" Compatibility with tmux
" set term=screen-256color
if has("mouse_sgr")
	set ttymouse=sgr
else
	set ttymouse=xterm2
end

" If problems with regexes in vim-javascript, uncomment below
" set regexpengine=1

"set t_Co=256						" Set 256 colors
if &t_Co == 256 || has("gui_running")
	syntax enable
	"set background=dark		" Set dark background
	"let g:solarized_termcolors=256
	colorscheme hybrid
endif

" Ultisnip keymap
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<s-tab>"

" Vim leader/localleader
let mapleader=","					" Main shortcuts
let localleader=' '					" Localleader to avoid conflicts

" Set correct runtimepath
set nocompatible
execute pathogen#infect()
execute pathogen#helptags()
filetype plugin indent on 			" Load file specific plugins/indent settings

" Open man pages in vim
source $VIMRUNTIME/ftplugin/man.vim
nnoremap K :Man <cword><cr><c-w>L

" Syntastic C flags
let g:syntastic_c_compiler = "clang"
let g:syntastic_c_compiler_options = "-Wall -Wextra"
let g:syntastic_c_include_dirs = ['libft/inc']
let g:syntastic_c_check_header = "1"
"let g:syntastic_cpp_check_header = 1
"let g:syntastic_html_tidy_exec = 'tidy5'

" Syntastic javascript
let g:syntastic_javascript_checkers = ['eslint']

" ignore whitespaces in vimdiff
set diffopt+=iwhite

" set foldcolumn=4
set mouse+=a

set foldmethod=indent
set encoding=utf8					" Set correct encoding
set backspace=indent,eol,start		" Fix backspace
set hidden							" Allow to hide buffer instead of closing it
set tabstop=4						" <tab> is 4 spaces large	
set shiftwidth=4					" Indent with 4 spaces
set smarttab						" Intelligent <tab> insertion
set autoindent						" Keep same indent on newline
set cindent							" Use C-style indentation
set hlsearch						" Highlight search results
set number							" Display line number 
set laststatus=2					" Always show status line
set statusline=%f\ -\ %y%=\ %l/%L\ [%c]%{SyntasticStatuslineFlag()}\ %m
set cursorline						" Display current line
set showmatch						" Display matching braces
set showcmd							" Show commands as you type them
set showmode						" Always show the current mode
set wildmenu						" Show more results on <tab>
set wildmode=list:longest,full		" Show them all
set splitbelow						" Force new windows to open below..
set splitright						" .. on the right

" Do not set .h files as cpp
autocmd BufNewFile,BufReadPost *.h setlocal filetype=c
autocmd BufWritePost,BufReadPost *.tpp setlocal filetype=cpp
autocmd BufNewFile,BufReadPost *.md setlocal filetype=markdown

autocmd FileType h,c,cpp setlocal colorcolumn=80
autocmd FileType help,man wincmd L					" Display man/help pages in a split

" Hit <esc> quicker
inoremap jk <esc>
snoremap jk <esc>

" Disable highlighting
nnoremap <leader>/ :nohlsearch<cr>
inoremap <leader>/ :nohlsearch<cr>

" Navigate through wrapped lines
nnoremap j gj
nnoremap k gk
vnoremap j gj
vnoremap k gk

" Navigate through tabs
nnoremap <c-l> :tabnext<cr>
nnoremap <c-h> :tabprevious<cr>
nnoremap <c-n> :tabnew<cr>
nnoremap <c-c> :tabclose<cr>
nnoremap <c-e> :tabedit 

"Navigate through splits
nnoremap <Tab>l <c-w>l
nnoremap <Tab>h <c-w>h
nnoremap <Tab>j <c-w>j
nnoremap <Tab>k <c-w>k

" Quick access to NERDTree
nnoremap <leader>b :NERDTreeToggle<cr>

" Quickly edit vimrc
nnoremap <leader>ev :vs ~/.vim/vimrc<cr>

" Quickly edit snippets
nnoremap <leader>sni :vs ~/.vim/bundle/vim-snippets/snippets<cr>

" Save / Close files
nnoremap <leader>w :w<cr>
nnoremap <leader>q :q<cr>
nnoremap <leader>wq :wq<cr>

" Faster autocomplete
inoremap <c-o> <c-n>
